name: deploy-pr
on:
  pull_request:
    paths:
      - "app/**"
      - .github/workflows/deploy-pr.yml

env:
  Registory: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checout repository
        uses: actions/chaeckout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.Registory }}/${{ github.repository }} # ghcr.io/haseybrownrock/fastapi-sample

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.Registory }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: app/**
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels}}
